language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DBUILD_TESTS=ON"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated g++ libboost-all-dev

install:
- mkdir build
- cd build
- cmake $CMAKE_OPTIONS ..
- make

script:
- ./bin/yawiel_test -r detailed
