language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++
            - boost1.68
      env: CMAKE_OPTIONS="-D BUILD_TESTS=ON"
#      before_install:
#        - sudo add-apt-repository -y ppa:mhier/libboost-latest
#        - sudo apt-get update
#        - sudo apt-get install -y --allow-unauthenticated g++ boost1.68 cmake

install:
- mkdir build
- cd build
- cmake $CMAKE_OPTIONS ..
- make

script:
- ./bin/yawiel_test -r detailed
