language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++
            - boost1.67
            - libomp-dev
      env: CMAKE_OPTIONS="-D BUILD_TESTS=ON STATIC_BUILD=OFF OMP=ON"
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - g++
            - boost1.67
            - libomp-dev
      env: CMAKE_OPTIONS="-D BUILD_TESTS=ON STATIC_BUILD=ON OMP=OFF" 

install:
- mkdir build
- cd build
- cmake $CMAKE_OPTIONS ../
- make

script:
- ./bin/yawiel_test -r detailed
